package pl.polsl.biai.view;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.util.ArrayList;
import javax.swing.JFrame;
import pl.polsl.biai.controller.TheTravellingSalesmanProblem;
import pl.polsl.biai.domain.SingleTour;

/**
 *
 * @author Marta Miler
 */
public class GraphGUI extends javax.swing.JPanel {

   private static final int MAX_SCORE =100;
   private static final int PREF_W = 500;
   private static final int PREF_H = 500;
   private static final int BORDER_GAP = 5;
   private static final Color GRAPH_COLOR = Color.green;
   private static final Color GRAPH_POINT_COLOR = Color.red;
   private static final Stroke GRAPH_STROKE = new BasicStroke(2f);
   private static final int GRAPH_POINT_WIDTH = 10;
   private static final int Y_HATCH_CNT = 10;
   private SingleTour tour;
   
    /**
     * Creates new form DrawGraph
     */
 public GraphGUI(SingleTour tour) {
      this.tour = tour;
   }
 
 @Override
   protected void paintComponent(Graphics g) {
      super.paintComponent(g);
      Graphics2D g2 = (Graphics2D)g;
      g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

      //Scaling x and y to component width and height
      double xScale = ((double) getWidth() - 2 * BORDER_GAP) / (MAX_SCORE - 1);
      double yScale = ((double) getHeight() - 2 * BORDER_GAP) / (MAX_SCORE - 1);
      
      //Array of new points (cities)
      ArrayList<Point> graphPoints = new ArrayList<Point>();
      for (int i = 0; i < tour.getSingleTourSize(); i++) {
         int x1 = (int)((tour.getCityFromSingleTour(i).getX())* xScale + BORDER_GAP);
         int y1 = (int)(tour.getCityFromSingleTour(i).getY()*yScale + BORDER_GAP);
         graphPoints.add(new Point(x1, y1));
      }
      
      //Adding city 0 at the end
         int city0x = (int)((tour.getCityFromSingleTour(0).getX())* xScale + BORDER_GAP);
         int city0y = (int)(tour.getCityFromSingleTour(0).getY()*yScale + BORDER_GAP);
         graphPoints.add(new Point(city0x, city0y));

      // create x and y axes 
      g2.drawLine(BORDER_GAP, getHeight() - BORDER_GAP, BORDER_GAP, BORDER_GAP);
      g2.drawLine(BORDER_GAP, getHeight() - BORDER_GAP, getWidth() - BORDER_GAP, getHeight() - BORDER_GAP);

      // create hatch marks for y axis. 
      for (int i = 0; i < Y_HATCH_CNT; i++) {
         int x0 = BORDER_GAP;
         int x1 = GRAPH_POINT_WIDTH + BORDER_GAP;
         int y0 = getHeight() - (((i + 1) * (getHeight() - BORDER_GAP * 2)) / Y_HATCH_CNT + BORDER_GAP);
         int y1 = y0;
         g2.drawLine(x0, y0, x1, y1);
      }

      // and for x axis
      for (int i = 0; i < tour.getSingleTourSize() - 1; i++) {
         int x0 = (i + 1) * (getWidth() - BORDER_GAP * 2) / (tour.getSingleTourSize() - 1) + BORDER_GAP;
         int x1 = x0;
         int y0 = getHeight() - BORDER_GAP;
         int y1 = y0 - GRAPH_POINT_WIDTH;
         g2.drawLine(x0, y0, x1, y1);
      }

      Stroke oldStroke = g2.getStroke();
      g2.setColor(GRAPH_COLOR);
      g2.setStroke(GRAPH_STROKE);
      for (int i = 0; i < graphPoints.size() - 1; i++) {
         int x1 = graphPoints.get(i).x;
         int y1 = graphPoints.get(i).y;
         int x2 = graphPoints.get(i + 1).x;
         int y2 = graphPoints.get(i + 1).y;
         g2.drawLine(x1, y1, x2, y2);         
      }

      g2.setStroke(oldStroke);      
      g2.setColor(GRAPH_POINT_COLOR);
      for (int i = 0; i < graphPoints.size(); i++) {
         int x = graphPoints.get(i).x - GRAPH_POINT_WIDTH / 2;
         int y = graphPoints.get(i).y - GRAPH_POINT_WIDTH / 2;;
         int ovalW = GRAPH_POINT_WIDTH;
         int ovalH = GRAPH_POINT_WIDTH;
         g2.fillOval(x, y, ovalW, ovalH);
      }
   }

   @Override
   public Dimension getPreferredSize() {
      return new Dimension(PREF_W, PREF_H);
   }
   
   public static void drawGraph(SingleTour tour) {
      TheTravellingSalesmanProblem tsp = new TheTravellingSalesmanProblem();
      GraphGUI mainPanel = new GraphGUI(tour);

      JFrame frame = new JFrame("TSP Result");  
      frame.getContentPane().add(mainPanel);
      frame.pack();
      frame.setLocationByPlatform(true);
      frame.setVisible(true);
      
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    }
